spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://mysql:3306/test
        username: test
        password: test926
        driver-class-name: com.mysql.jdbc.Driver
